export const fields = {
  description: "description",
  entranceWidth: "entranceWidth",
  entranceHeight: "entranceHeight",
  storageSpace: "storageSpace",
  pricePerDay: "pricePerDay",
  discount: "discount",
  state: "state",
  city: "city",
  pincode: "pincode",
  locality: "locality",
  type: "type",
  facilities: "facilities",
  listingImages: "listingImages",
};
